name: HousingRepairsOnline.AddressIngestion

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches:
      - main

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Authenticate nuget
        run: dotnet nuget add source --username ${{ secrets.NUGET_AUTH_GITHUB_USERNAME }} --password ${{ secrets.NUGET_AUTH_GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/City-of-Lincoln-Council/index.json"
      - name: Run dotnet format
        run: dotnet format --verify-no-changes HousingRepairsOnline.AddressIngestion.sln

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Authenticate nuget
        run: dotnet nuget add source --username ${{ secrets.NUGET_AUTH_GITHUB_USERNAME }} --password ${{ secrets.NUGET_AUTH_GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/City-of-Lincoln-Council/index.json"
      - name: Test
        run: dotnet test

  infrastructure:
#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: "Provision Infrastructure"
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: "./terraform"
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="resource_group_name=${{ secrets.RESOURCE_GROUP_NAME }}" -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}" -backend-config="container_name=${{ secrets.STATE_CONTAINER_NAME }}" -backend-config="key=${{ secrets.STATE_KEY_NAME }}"
      - name: Setup tfvars
        run: |
          touch env.tfvars
          echo "cosmos-connection-string    = \"${{ secrets.COSMOS_CONNECTION_STRING }}\"" >> env.tfvars
          echo "database-name    = \"${{ secrets.DATABASE_NAME }}\"" >> env.tfvars
          echo "project    = \"${{ secrets.PROJECT_NAME }}\"" >> env.tfvars
          echo "location    = \"${{ secrets.LOCATION }}\"" >> env.tfvars
          echo "resource-group    = \"${{ secrets.RESOURCE_GROUP_NAME }}\"" >> env.tfvars
          echo "storage-account    = \"${{ secrets.STORAGE_ACCOUNT_NAME }}\"" >> env.tfvars
          echo "app-service-plan    = \"${{ secrets.APP_SERVICE_PLAN }}\"" >> env.tfvars
          echo "storage-container-name    = \"${{ secrets.STATE_CONTAINER_NAME }}\"" >> env.tfvars
          echo "storage-account-primary-access-key    = \"${{ secrets.STORAGE_ACCOUNT_PRIMARY_ACCESS_KEY }}\"" >> env.tfvars

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -var-file="env.tfvars"

      - name: Terraform Apply
        id: terraform_apply
        run: terraform apply -auto-approve -var-file="env.tfvars"

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [infrastructure]
    steps:
      - name: 'Checkout GitHub action'
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Authenticate nuget
        run: dotnet nuget add source --username ${{ secrets.NUGET_AUTH_GITHUB_USERNAME }} --password ${{ secrets.NUGET_AUTH_GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/City-of-Lincoln-Council/index.json"

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './HousingRepairsOnline.AddressIngestion'
          dotnet build --configuration Release --output ./output
          popd

      - name: 'Run Azure Functions action'
        uses: Azure/functions-action@v1
        with:
          app-name: 'test-function-hro-maysa'
          package: 'HousingRepairsOnline.AddressIngestion/output'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
